# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='proto/messages.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x14proto/messages.proto\"\x8c\x04\n\x07request\x12\x10\n\x08\x66rom_mac\x18\x01 \x01(\x0c\x12\x0e\n\x06to_mac\x18\x02 \x01(\x0c\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x14\n\x0cmessage_type\x18\x04 \x01(\x05\x12&\n\noperations\x18\x05 \x03(\x0b\x32\x12.request.Operation\x1a+\n\x04Ping\x12\x16\n\x0eoperation_type\x18\x01 \x01(\x05\x12\x0b\n\x03num\x18\x02 \x01(\x05\x1aO\n\x04Send\x12\x16\n\x0eoperation_type\x18\x01 \x01(\x05\x12\r\n\x05queue\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x0f\n\x07persist\x18\x04 \x01(\x08\x1a\x32\n\tSubscribe\x12\x16\n\x0eoperation_type\x18\x01 \x01(\x05\x12\r\n\x05queue\x18\x02 \x01(\t\x1a\x34\n\x0bUnsubscribe\x12\x16\n\x0eoperation_type\x18\x01 \x01(\x05\x12\r\n\x05queue\x18\x02 \x01(\t\x1a\xa5\x01\n\tOperation\x12\x1d\n\x04ping\x18\x01 \x01(\x0b\x32\r.request.PingH\x00\x12\x1d\n\x04send\x18\x02 \x01(\x0b\x32\r.request.SendH\x00\x12\'\n\tsubscribe\x18\x03 \x01(\x0b\x32\x12.request.SubscribeH\x00\x12+\n\x0bunsubscribe\x18\x04 \x01(\x0b\x32\x14.request.UnsubscribeH\x00\x42\x04\n\x02op\"\xa0\x02\n\x08response\x12\x10\n\x08\x66rom_mac\x18\x01 \x01(\x0c\x12\x0e\n\x06to_mac\x18\x02 \x01(\x0c\x12\x14\n\x0cmessage_type\x18\x03 \x01(\x05\x12)\n\x0bopResponses\x18\x04 \x03(\x0b\x32\x14.response.OpResponse\x1a\\\n\nOpResponse\x12\x16\n\x0eoperation_type\x18\x01 \x01(\x05\x12%\n\x0bresult_code\x18\x02 \x01(\x0e\x32\x10.response.Result\x12\x0f\n\x07payload\x18\x03 \x01(\t\"S\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\x11\n\rSUBSCRIBED_OK\x10\x01\x12\x13\n\x0fUNSUBSCRIBED_OK\x10\x03\x12\t\n\x05\x45RROR\x10\x05\x12\x0e\n\nMQTT_ERROR\x10\x07\x62\x06proto3'
)

_RESPONSE_RESULT = _descriptor.EnumDescriptor(
    name='Result',
    full_name='response.Result',
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name='OK', index=0, number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='SUBSCRIBED_OK', index=1, number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='UNSUBSCRIBED_OK', index=2, number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='ERROR', index=3, number=5,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='MQTT_ERROR', index=4, number=7,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=757,
    serialized_end=840,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_RESULT)

_REQUEST_PING = _descriptor.Descriptor(
    name='Ping',
    full_name='request.Ping',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='operation_type', full_name='request.Ping.operation_type', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='num', full_name='request.Ping.num', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=151,
    serialized_end=194,
)

_REQUEST_SEND = _descriptor.Descriptor(
    name='Send',
    full_name='request.Send',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='operation_type', full_name='request.Send.operation_type', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='queue', full_name='request.Send.queue', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='payload', full_name='request.Send.payload', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='persist', full_name='request.Send.persist', index=3,
            number=4, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=196,
    serialized_end=275,
)

_REQUEST_SUBSCRIBE = _descriptor.Descriptor(
    name='Subscribe',
    full_name='request.Subscribe',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='operation_type', full_name='request.Subscribe.operation_type', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='queue', full_name='request.Subscribe.queue', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=277,
    serialized_end=327,
)

_REQUEST_UNSUBSCRIBE = _descriptor.Descriptor(
    name='Unsubscribe',
    full_name='request.Unsubscribe',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='operation_type', full_name='request.Unsubscribe.operation_type', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='queue', full_name='request.Unsubscribe.queue', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=329,
    serialized_end=381,
)

_REQUEST_OPERATION = _descriptor.Descriptor(
    name='Operation',
    full_name='request.Operation',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='ping', full_name='request.Operation.ping', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='send', full_name='request.Operation.send', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='subscribe', full_name='request.Operation.subscribe', index=2,
            number=3, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='unsubscribe', full_name='request.Operation.unsubscribe', index=3,
            number=4, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name='op', full_name='request.Operation.op',
            index=0, containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[]),
    ],
    serialized_start=384,
    serialized_end=549,
)

_REQUEST = _descriptor.Descriptor(
    name='request',
    full_name='request',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='from_mac', full_name='request.from_mac', index=0,
            number=1, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='to_mac', full_name='request.to_mac', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='client_id', full_name='request.client_id', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='message_type', full_name='request.message_type', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='operations', full_name='request.operations', index=4,
            number=5, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[_REQUEST_PING, _REQUEST_SEND, _REQUEST_SUBSCRIBE, _REQUEST_UNSUBSCRIBE, _REQUEST_OPERATION, ],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=25,
    serialized_end=549,
)

_RESPONSE_OPRESPONSE = _descriptor.Descriptor(
    name='OpResponse',
    full_name='response.OpResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='operation_type', full_name='response.OpResponse.operation_type', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='result_code', full_name='response.OpResponse.result_code', index=1,
            number=2, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='payload', full_name='response.OpResponse.payload', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=663,
    serialized_end=755,
)

_RESPONSE = _descriptor.Descriptor(
    name='response',
    full_name='response',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='from_mac', full_name='response.from_mac', index=0,
            number=1, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='to_mac', full_name='response.to_mac', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='message_type', full_name='response.message_type', index=2,
            number=3, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='opResponses', full_name='response.opResponses', index=3,
            number=4, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[_RESPONSE_OPRESPONSE, ],
    enum_types=[
        _RESPONSE_RESULT,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=552,
    serialized_end=840,
)

_REQUEST_PING.containing_type = _REQUEST
_REQUEST_SEND.containing_type = _REQUEST
_REQUEST_SUBSCRIBE.containing_type = _REQUEST
_REQUEST_UNSUBSCRIBE.containing_type = _REQUEST
_REQUEST_OPERATION.fields_by_name['ping'].message_type = _REQUEST_PING
_REQUEST_OPERATION.fields_by_name['send'].message_type = _REQUEST_SEND
_REQUEST_OPERATION.fields_by_name['subscribe'].message_type = _REQUEST_SUBSCRIBE
_REQUEST_OPERATION.fields_by_name['unsubscribe'].message_type = _REQUEST_UNSUBSCRIBE
_REQUEST_OPERATION.containing_type = _REQUEST
_REQUEST_OPERATION.oneofs_by_name['op'].fields.append(
    _REQUEST_OPERATION.fields_by_name['ping'])
_REQUEST_OPERATION.fields_by_name['ping'].containing_oneof = _REQUEST_OPERATION.oneofs_by_name['op']
_REQUEST_OPERATION.oneofs_by_name['op'].fields.append(
    _REQUEST_OPERATION.fields_by_name['send'])
_REQUEST_OPERATION.fields_by_name['send'].containing_oneof = _REQUEST_OPERATION.oneofs_by_name['op']
_REQUEST_OPERATION.oneofs_by_name['op'].fields.append(
    _REQUEST_OPERATION.fields_by_name['subscribe'])
_REQUEST_OPERATION.fields_by_name['subscribe'].containing_oneof = _REQUEST_OPERATION.oneofs_by_name['op']
_REQUEST_OPERATION.oneofs_by_name['op'].fields.append(
    _REQUEST_OPERATION.fields_by_name['unsubscribe'])
_REQUEST_OPERATION.fields_by_name['unsubscribe'].containing_oneof = _REQUEST_OPERATION.oneofs_by_name['op']
_REQUEST.fields_by_name['operations'].message_type = _REQUEST_OPERATION
_RESPONSE_OPRESPONSE.fields_by_name['result_code'].enum_type = _RESPONSE_RESULT
_RESPONSE_OPRESPONSE.containing_type = _RESPONSE
_RESPONSE.fields_by_name['opResponses'].message_type = _RESPONSE_OPRESPONSE
_RESPONSE_RESULT.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['request'] = _REQUEST
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {

    'Ping': _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), {
        'DESCRIPTOR': _REQUEST_PING,
        '__module__': 'proto.messages_pb2'
        # @@protoc_insertion_point(class_scope:request.Ping)
    })
    ,

    'Send': _reflection.GeneratedProtocolMessageType('Send', (_message.Message,), {
        'DESCRIPTOR': _REQUEST_SEND,
        '__module__': 'proto.messages_pb2'
        # @@protoc_insertion_point(class_scope:request.Send)
    })
    ,

    'Subscribe': _reflection.GeneratedProtocolMessageType('Subscribe', (_message.Message,), {
        'DESCRIPTOR': _REQUEST_SUBSCRIBE,
        '__module__': 'proto.messages_pb2'
        # @@protoc_insertion_point(class_scope:request.Subscribe)
    })
    ,

    'Unsubscribe': _reflection.GeneratedProtocolMessageType('Unsubscribe', (_message.Message,), {
        'DESCRIPTOR': _REQUEST_UNSUBSCRIBE,
        '__module__': 'proto.messages_pb2'
        # @@protoc_insertion_point(class_scope:request.Unsubscribe)
    })
    ,

    'Operation': _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), {
        'DESCRIPTOR': _REQUEST_OPERATION,
        '__module__': 'proto.messages_pb2'
        # @@protoc_insertion_point(class_scope:request.Operation)
    })
    ,
    'DESCRIPTOR': _REQUEST,
    '__module__': 'proto.messages_pb2'
    # @@protoc_insertion_point(class_scope:request)
})
_sym_db.RegisterMessage(request)
_sym_db.RegisterMessage(request.Ping)
_sym_db.RegisterMessage(request.Send)
_sym_db.RegisterMessage(request.Subscribe)
_sym_db.RegisterMessage(request.Unsubscribe)
_sym_db.RegisterMessage(request.Operation)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {

    'OpResponse': _reflection.GeneratedProtocolMessageType('OpResponse', (_message.Message,), {
        'DESCRIPTOR': _RESPONSE_OPRESPONSE,
        '__module__': 'proto.messages_pb2'
        # @@protoc_insertion_point(class_scope:response.OpResponse)
    })
    ,
    'DESCRIPTOR': _RESPONSE,
    '__module__': 'proto.messages_pb2'
    # @@protoc_insertion_point(class_scope:response)
})
_sym_db.RegisterMessage(response)
_sym_db.RegisterMessage(response.OpResponse)

# @@protoc_insertion_point(module_scope)
